"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY: declared in base but intentionally left unset here.
# - dev.py provides a permissive fallback so local runs and tests "just work".
# - prod.py requires DJANGO_SECRET_KEY to be present in the environment and
#   will raise ImproperlyConfigured at startup otherwise (fail-fast).
SECRET_KEY: str | None = os.getenv("DJANGO_SECRET_KEY")

# Coop location — used for sunrise/sunset shading on the timeline.
# Defaults to London if not set.
COOP_LATITUDE = float(os.getenv("COOP_LATITUDE", "51.5"))
COOP_LONGITUDE = float(os.getenv("COOP_LONGITUDE", "-0.1"))


# The app is deployed behind a LAN + VPN boundary, so ALLOWED_HOSTS = ["*"]
# in base is acceptable. prod.py may tighten this if desired.
ALLOWED_HOSTS = [
    "*",
]


# Application definition

INSTALLED_APPS = [
    "web_app.apps.WebAppConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "django_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_project.wsgi.application"

# --- Logging ---
#
# Tunable via environment variables:
#
#   LOG_DIR      — directory for rotating log files
#                  (default: <repo>/logs — works for local dev; override in
#                  prod/Docker to e.g. /var/log/chicken-watcher or a mounted
#                  volume).
#   LOG_FILENAME — filename within LOG_DIR (default: django.log). Each service
#                  (web, hardware agent, scheduler) sets its own.
#   LOG_LEVEL    — root level; INFO in prod, DEBUG in dev (opt-in).
#                  10–100× fewer lines at INFO than DEBUG, which matters for
#                  SD-card longevity on the Pi.
#   LOG_FILE_BYTES       — rotation threshold per file (default 10 MiB).
#   LOG_FILE_BACKUP_COUNT — number of rotated backups to keep (default 5).
LOGS_DIR = os.getenv("LOG_DIR") or os.path.join(BASE_DIR, "logs")

# Create the logs dir if we can; if we can't (read-only FS, permission
# denied), fall back to a stderr-only config rather than crashing at import.
try:
    os.makedirs(LOGS_DIR, exist_ok=True)
    _logs_dir_writable = os.access(LOGS_DIR, os.W_OK)
except OSError:
    _logs_dir_writable = False

_log_filename = os.getenv("LOG_FILENAME", "django.log")
_log_level = os.getenv("LOG_LEVEL", "INFO").upper()
_log_file_bytes = int(os.getenv("LOG_FILE_BYTES", str(10 * 1024 * 1024)))
_log_file_backups = int(os.getenv("LOG_FILE_BACKUP_COUNT", "5"))

_log_handlers: dict = {
    "console": {
        "class": "logging.StreamHandler",
        "level": _log_level,
        "formatter": "simple",
    },
}
_root_handlers = ["console"]

if _logs_dir_writable:
    _log_handlers["file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "level": _log_level,
        "formatter": "verbose",
        "filename": os.path.join(LOGS_DIR, _log_filename),
        "maxBytes": _log_file_bytes,
        "backupCount": _log_file_backups,
        "encoding": "utf-8",
    }
    _root_handlers.append("file")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname:8s} {name} | {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname:8s} {message}",
            "style": "{",
        },
    },
    "handlers": _log_handlers,
    # Root logger. DEBUG in dev (opt-in via LOG_LEVEL=DEBUG), INFO in prod.
    # A per-logger override below silences the very chatty Django DB logger
    # at DEBUG — if you really want SQL echo, set DJANGO_DB_LOG_LEVEL=DEBUG.
    "root": {
        "handlers": _root_handlers,
        "level": _log_level,
    },
    "loggers": {
        # Third-party libraries that default to very verbose output are
        # pinned to INFO so LOG_LEVEL=DEBUG doesn't drown us in upstream
        # noise. Override DJANGO_DB_LOG_LEVEL to opt in to SQL echo.
        "django.db.backends": {
            "level": os.getenv("DJANGO_DB_LOG_LEVEL", "INFO"),
            "handlers": _root_handlers,
            "propagate": False,
        },
        "django.utils.autoreload": {
            "level": "INFO",
            "handlers": _root_handlers,
            "propagate": False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", BASE_DIR / "static")

MEDIA_URL = "media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", BASE_DIR / "media")
