services:
  hardware-agent:
    build: .
    command: ["python", "manage.py", "run_hardware_agent"]
    privileged: true
    environment:
      - DJANGO_ENV=prod
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MEDIA_ROOT=/app/media
      - RFID_PORT_BY_ID_LEFT=${RFID_PORT_BY_ID_LEFT}
      - RFID_PORT_BY_ID_RIGHT=${RFID_PORT_BY_ID_RIGHT}
      - CAMERA_DEVICE_BY_ID=${CAMERA_DEVICE_BY_ID}
      - BEAM_BREAK_GPIO_LEFT=${BEAM_BREAK_GPIO_LEFT}
      - BEAM_BREAK_GPIO_RIGHT=${BEAM_BREAK_GPIO_RIGHT}
    volumes:
      - media_volume:/app/media
      - /dev:/dev
    restart: unless-stopped
    depends_on:
      - db

  web-app:
    build: .
    environment:
      - DJANGO_ENV=prod
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MEDIA_ROOT=/app/media
      - STATIC_ROOT=/app/static
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
#      interval: 5s
#      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

volumes:
  media_volume:
  static_volume:
  pgdata:
