# Generated by Django 6.0 on 2025-12-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chicken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                ("date_of_death", models.DateField()),
                ("tag_string", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="NestingBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Egg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("laid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chicken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eggs.chicken"
                    ),
                ),
                (
                    "nesting_box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eggs.nestingbox",
                    ),
                ),
            ],
        ),
    ]
