# Generated by Django 6.0 on 2025-12-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eggs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chicken",
            name="date_of_death",
            field=models.DateField(blank=True, null=True),
        ),
    ]
