# Generated by Django 6.0 on 2025-12-27 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eggs", "0002_alter_chicken_date_of_death"),
    ]

    operations = [
        migrations.CreateModel(
            name="NestingBoxVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chicken",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eggs.chicken"
                    ),
                ),
                (
                    "nesting_box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eggs.nestingbox",
                    ),
                ),
            ],
        ),
    ]
