# Generated by Django 6.0 on 2025-12-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eggs", "0003_nestingboxvisit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egg",
            name="laid_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="nestingboxvisit",
            name="ended_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
