# Generated by Django 6.0 on 2025-12-27 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eggs", "0004_alter_egg_laid_at_alter_nestingboxvisit_ended_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egg",
            name="laid_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="nestingboxvisit",
            name="ended_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
