# Generated by Django 6.0 on 2025-12-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eggs", "0005_alter_egg_laid_at_alter_nestingboxvisit_ended_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="nestingboxvisit",
            constraint=models.CheckConstraint(
                condition=models.Q(("started_at__lte", models.F("ended_at"))),
                name="started_before_ended",
            ),
        ),
    ]
