# Generated by Django 6.0 on 2025-12-28 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_nestingboxpresence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestingboxpresence',
            name='present_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
