# Generated by Django 6.0 on 2025-12-29 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0003_alter_nestingboxpresence_present_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nestingboxpresence",
            options={
                "verbose_name": "nesting box",
                "verbose_name_plural": "nesting boxes",
            },
        ),
    ]
