# Generated by Django 6.0 on 2025-12-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_alter_nestingboxpresence_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nestingbox',
            options={'verbose_name': 'nesting box', 'verbose_name_plural': 'nesting boxes'},
        ),
        migrations.AlterModelOptions(
            name='nestingboxpresence',
            options={},
        ),
    ]
