# Generated by Django 6.0 on 2025-12-29 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0005_alter_nestingbox_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nestingbox",
            options={"verbose_name_plural": "nesting boxes"},
        ),
    ]
