# Generated by Django 6.0 on 2025-12-31 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0006_alter_nestingbox_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="NestingBoxImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("image", models.ImageField(upload_to="nesting_box_images")),
            ],
        ),
    ]
