# Generated by Django 6.0 on 2026-01-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0007_nestingboximage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egg",
            name="chicken",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_app.chicken",
            ),
        ),
    ]
