# Generated by Django 6.0 on 2026-01-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0008_alter_egg_chicken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egg",
            name="chicken",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_app.chicken",
            ),
        ),
        migrations.AlterField(
            model_name="egg",
            name="nesting_box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web_app.nestingbox",
            ),
        ),
    ]
