# Generated by Django 6.0 on 2026-04-03 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0012_alter_egg_laid_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nestingboxpresence",
            name="present_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="nestingboxpresenceperiod",
            name="ended_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="nestingboxpresenceperiod",
            name="started_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
