# Generated by Django 6.0 on 2026-04-04 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0013_reindex_presence_period_presence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nestingboximage",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
