# Generated by Django 6.0 on 2026-04-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0014_alter_nestingboximage_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfid_string", models.CharField(max_length=200, unique=True)),
                ("number", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="chicken",
            name="tag_string",
        ),
        migrations.AddField(
            model_name="chicken",
            name="tag",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chicken",
                to="web_app.tag",
            ),
        ),
    ]
