# Generated by Django 6.0 on 2026-04-04 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0015_add_tag_model_and_refactor_chicken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chicken",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chickens",
                to="web_app.tag",
            ),
        ),
    ]
