# Generated by Django 6.0 on 2026-04-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0017_add_dud_to_egg"),
    ]

    operations = [
        migrations.AddField(
            model_name="nestingboxpresence",
            name="sensor_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="nestingboxpresenceperiod",
            name="sensor_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
