# Generated by Django 6.0 on 2026-04-06 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0018_nestingboxpresence_sensor_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nestingboxpresenceperiod",
            name="sensor_id",
        ),
    ]
