# Generated by Django 6.0 on 2026-05-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0024_add_default_orderings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardwaresensor",
            name="is_connected",
        ),
        migrations.AddField(
            model_name="hardwaresensor",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("degraded", "Temporarily offline"),
                    ("offline", "Offline"),
                ],
                default="offline",
                max_length=10,
            ),
        ),
    ]
